export const PHASE_PLAY = "PHASE_PLAY"
export const PHASE_DRAW = "PHASE_DRAW"
export const PHASE_SWAP = "PHASE_SWAP"
export const PHASE_PEEK = "PHASE_PEEK"

export const DRAW_PILE = "DRAW_PILE"
export const DISCARD_PILE = "DISCARD_PILE"

export const CARD_ACTION_SWAP = "CARD_ACTION_SWAP"
export const CARD_ACTION_HAND = "CARD_ACTION_HAND"
export const CARD_ACTION_SELECT = "CARD_ACTION_SELECT"