export const CREATE_LOBBY_ID = "CREATE_LOBBY_ID"
export const SET_LOBBY_ID = "SET_LOBBY_ID"
export const GET_LOBBY_ID = "GET_LOBBY_ID"
export const DELETE_LOBBY_ID = "DELETE_LOBBY_ID"

export const INIT_DECK = "INIT_DECK"
export const UPDATE_PHASE = "UPDATE_PHASE"
export const DRAW_CARD = "DRAW_CARD"
export const PLAY_CARD = "PLAY_CARD"
export const UPDATE_DECK = "UPDATE_DECK"
export const REBUILD_DECK = "REBUILD_DECK"

export const INIT_PLAYERS = "INIT_PLAYERS"
export const INIT_PLAYER = "INIT_PLAYER"
export const INIT_GAME = "INIT_GAME"
export const ADD_CARD = "ADD_CARD"
export const DEAL_CARD = "DEAL_CARD"
export const SWAP_CARDS = "SWAP_CARDS"
export const SLAP_CARDS = "SLAP_CARDS"
export const UPDATE_HAND = "UPDATE_HAND"

export const ROUND_LAUNCH = "ROUND_LAUNCH"
export const ROUND_END = "ROUND_END"